import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const packageJsonPath = resolve(repoRoot, 'package.json');
const versionPath = resolve(repoRoot, 'src', 'version.ts');

const packageJson = JSON.parse(await readFile(packageJsonPath, 'utf8'));

if (typeof packageJson.version !== 'string' || packageJson.version.length === 0) {
  throw new Error('package.json must define a non-empty version string');
}

const source = `// Generated by scripts/sync-version.mjs; do not edit manually.
export const VERSION = '${packageJson.version}';
`;

await writeFile(versionPath, source);
